site_name: Kamailio KEMI Framework
theme: readthedocs
extra_css: [extra.css]
nav:
    - 'Kamailio KEMI Framework': 'index.md'
    - 'KEMI Interpreters': 'kemi.md'
    - 'Core And PV Functions': 'core.md'
    - 'Special Functions': 'kemimods.md'
    - 'Module Functions': 'modules.md'
    - 'Support': 'support.md'
    - 'Contributions': 'contributions.md'
markdown_extensions:
    - toc:
        permalink: Link